export class Product {
    Row: number;
    ImagePath: string;
    ProductCode: string;
    Product:string;
    Season:string;
    Category1:string;
    Category2:string;
    Category3:string;
    Category4:string;
    Category5:string;
    OriginalSell:number;
    PerformanceRank:number;
    PerformanceRating:string;
    ConversionRate:number;
    ReturnRate:number;
    ClickThroughRate:number;
    Impression:number;
    CostPrice:number;
    FPMD:string;
    TDSales:number;
    TDRcvdUnits:number;
    SOH:number;
    WOS:number;
    TDST:number;
    WeeksInStore:number;
    ImagePathThumbnail:string;
    ImagePathTile:string;
    _Count:number;
    PreviousWos:number;
    Details:string;
}
